### ISSUE TITLE
Pow R2 Esphome

### ISSUE THREAD

**Issue by sebastien-savalle** [alvarea/Home-Assistant#1]
Hello @alvarea ,

Sorry to disturb you on this repository but I don't find other way to contact you.
I'm contacting you about EspHome because I have a similar issue. https://github.com/esphome/issues/issues/1

Are you still using EspHome to control the SonOff Pow R2
Could you send me your working configuration for the Pow R2 ? 

Thanks in advance.
Sébastien

**Comment by alvarea** [comment]
Hi Sebastien,  

Sorry I didn't see your msg.  You can reach me at my discord in case you still need help with the Sonoff Pow R2.  Regards.
